### ISSUE TITLE
Image save enabling

### ISSUE THREAD

**Issue by cproduct** [cproduct/Halftone#12]
- Startup config to enable / disable dither image
- File name algorithmn

**Comment by pichuio** [comment]
the command line argument

   - saveFiles 

is added, if arg is True, the Files get saved, if the arg is False only the dither algorithm with time measurement runs, files will not be saved

**Comment by cproduct** [comment]
Dither image should be saved in same directory of original image. (this is a requirement)

**Comment by cproduct** [comment]
Done image file name.
Example:
Original: sample.jpg --> sample_seq.jpg & sample_par.jpg
