### ISSUE TITLE
JUnit Version Update

### ISSUE THREAD

**Issue by cproduct** [cproduct/Halftone#9]
Annotations
Pom

**Comment by pichuio** [comment]
i will add this feature now...should not take long

**Comment by pichuio** [comment]
junit 4.12 full implemented

**Comment by cproduct** [comment]
Not done correctly. Deprecated assert calls used. See http://www.cavdar.net/2008/07/21/junit-4-in-60-seconds

Example: Assert.areEquals is deprecated. Only areEquals instead

**Comment by cproduct** [comment]
Seriosly? See others: Assert.fail vor Assert.areXXX
